import './globals.css';
import { Raleway } from 'next/font/google';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Website Demo',
  description: 'Generated by Bishal Moktan',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`container ${raleway.className}`}>
        <div className="wrapper">{children}</div>
      </body>
    </html>
  );
}
