import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Website Demo',
  description: 'Generated by Bishal Moktan',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`container ${inter.className}`}>
        <div className="wrapper">{children}</div>
      </body>
    </html>
  );
}
